### ISSUE TITLE
load nginx.conf failed

### ISSUE THREAD

**Issue by bijingrui** [peakwinter/python-nginx#28]
Dear sir:
    Unexpected results when parsing the limit_except block using the loadf method.
    E.g.

    location /M01 {
            proxy_pass http://backend;
            limit_except GET POST {deny all;}
    }

    The result of parsing using loadf is as follows
                       {
                            "location /M01": [
                                {
                                    "proxy_pass": "http://backend"
                                },
                                {
                                    "limit_except": "GET POST {\n                deny all"
                                }
                            ]
                        }
   Obviously, there was an error in parsing the limit_except block. I guess it was caused by ";" after "deny all". Can you solve it? Thank you.

**Comment by fulder** [comment]
I couldn't really reproduce this issue using version 1.5 because the parsing crashed with your example location:

```
...
"nginx.py", line 470, in loads
    if isinstance(lopen[0], Container):
IndexError: list index out of range
```

After enabling the `limit_except` parsing in #29 and using `loadf` followed by `dumpf` I get a result file with content:

```
location /M01 {
    proxy_pass http://backend;

    limit_except GET POST {
        deny all;
    }
}
```

**Comment by AcidRaZor** [comment]
Looks like a copy/paste issue to the config where "\n " was included in the paste and when trying to loadf he encountered the error? I can't reproduce either unless @bijingrui can perhaps go through the steps they used that lead to this?

**Comment by bijingrui** [comment]
As you said, when parsing the limit_except statement block, the method crashes. Is there any defect in the `loads` function? @fulder

**Comment by fulder** [comment]
The current version just doesn't recognize `limit_expect` blocks so it crashes. My PR turns the on the parsing of `limit_expect` again. Could you try if you get it working using my fork?

**Comment by bijingrui** [comment]
wow！
Test passed, thank you for your help.
