### ISSUE TITLE
Documentation: Request example of editing a configuration

### ISSUE THREAD

**Issue by danielloader** [peakwinter/python-nginx#34]
Thanks for this tool, it's great! 
Just one question, is there any chance of an example of how to load a file and edit a key:value pair in the configuration?

**Comment by peakwinter** [comment]
Hi Daniel,

Yes, you can do so by finding the key and then setting its `value`. Something like this:

```python
import nginx

c = nginx.loadf('/etc/nginx/sites-available/testsite')
keys = c.server.filter('Key', 'name_of_key_you_want_to_edit')
print(keys[0].value)  # 'existing value of the key'
keys[0].value = 'new value of my key'
print(keys[0].value)  # 'new value of my key'

# Save the changes
nginx.dumpf(c, '/etc/nginx/sites-available/testsite')
```

**Comment by danielloader** [comment]
Thanks for the prompt response, I've managed to get something on the root level of the server configuration such as server_name to change/write out to file, finding it a bit more difficult to guess the syntax to change a proxy_set_header directive inside a location block. 

Sorry for the questions, though happy to put in a pull request after to add documentation if you want a more verbose readme.md.

**Comment by peakwinter** [comment]
In this case, after having loaded the file, you can access that key with:

```python
c.server.locations[0].filter('Key', 'proxy_set_header')[0]
```

**Comment by danielloader** [comment]
Ah perfect, it was the lack of adding array index that scuppered me, should have realised!

Thanks for the tool it's extremely useful.

**Comment by peakwinter** [comment]
Not strictly using, the library, no, but here's how I'd do so otherwise:

```python
all_keys = c.server.filter('Location', '/')[0].filter('Key', 'proxy_set_header')
the_key = next((x for x in all_keys if x.value == 'value_im_looking_for'), None)
```

**Comment by danielloader** [comment]
Yeah figured could always fall back to python after all, thanks for all your help.
