### ISSUE TITLE
argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by quanghuy1288** [peakwinter/python-nginx#38]
version 1.5.4
When using function 'as_strings', error show as this:

`lib/python2.7/site-packages/nginx.py", line 402, in as_strings
    if '"' not in self.value and (';' in self.value or '#' in self.value):
TypeError: argument of type 'int' is not iterable`

**Comment by peakwinter** [comment]
@quanghuy1288 This should be fixed in 1.5.5. Thanks for reporting!
