### ISSUE TITLE
list index out of range when location contains curly braces

### ISSUE THREAD

**Issue by rebrendov** [peakwinter/python-nginx#40]
**How to reproduce**:
1. Create nginx.conf with
```
server {
    listen 80;
    server_name test.example.com;

    location ~ "^/(test|[0-9a-zA-Z]{6})$" {
        if ($query_string ~ pid=(111)) {
            return 403;
        }

        proxy_pass http://127.0.0.1:81;
    }
}
```
2. Create a test.py script
```python
import nginx
import os

conf_ast = nginx.loadf("./nginx.conf")
```
3. Run `python test.py`.

**Expected result**: config is successfully parsed.
**Actual  result**:
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    conf_ast = nginx.loadf("./nginx.conf")
  File "/home/user/Downloads/tmp/parsing-debug/lib/python3.8/site-packages/nginx.py", line 556, in loadf
    return load(f)
  File "/home/user/Downloads/tmp/parsing-debug/lib/python3.8/site-packages/nginx.py", line 546, in load
    return loads(fobj.read())
  File "/home/user/Downloads/tmp/parsing-debug/lib/python3.8/site-packages/nginx.py", line 500, in loads
    if isinstance(lopen[0], Container):
IndexError: list index out of range
```

This happens because this regex https://github.com/peakwinter/python-nginx/blob/1.5.4/nginx.py#L447 incorrectly considers curly braces as a starting point of a location block.
I can think of a couple of ways to fix this like adding `+` so it would be `^\s*location\s*([^;]*?)\s+{` instead of `^\s*location\s*([^;]*?)\s*{` or adding `\n` at the end. But I'm not sure which one is better.

**Comment by peakwinter** [comment]
@rebrendov This should be fixed in 1.5.5. Thanks for reporting!
