### ISSUE TITLE
Failing parsing without new line at the end of file

### ISSUE THREAD

**Issue by AlexNik** [peakwinter/python-nginx#41]
Hello!

I'm using 1.5.5
It failed when parsing this file
```
user  nginx;
```
Here is the error: `nginx.ParseError: Config syntax, missing ';' at index: 12`

But works fine when there is a new line at the end:
```
user  nginx;

```

**Comment by AlexNik** [comment]
UPD
With many new liney there is the error too
```
user  nginx;


```

**Comment by peakwinter** [comment]
Should be corrected in 1.5.6. Thank you!
