### ISSUE TITLE
Nginx.py is not working with python3 module (ModuleNotFoundError: No module named 'nginx')

### ISSUE THREAD

**Issue by arymangupta** [peakwinter/python-nginx#45]
autoprov.py
#############
import nginx
c = nginx.loadf(confLocation)

Installed using pyinstaller 

 pyinstaller --onefile ../src/autoprov/autoprov.py

2556 INFO: Analyzing XXX/pybuild/autoprov.py
2574 INFO: Processing module hooks...
2574 INFO: Loading module hook "hook-encodings.py"...
2625 INFO: Loading module hook "hook-pydoc.py"...
2626 INFO: Loading module hook "hook-xml.py"...
2814 INFO: Looking for ctypes DLLs
2814 INFO: Analyzing run-time hooks ...
2819 INFO: Looking for dynamic libraries
3070 INFO: Looking for eggs
3070 INFO: Using Python library /lib64/libpython3.6m.so.1.0
3075 INFO: Warnings written to XXX/pybuild/build/autoprov/warn-autoprov.txt
3096 INFO: Graph cross-reference written to XXX/build/autoprov/xref-autoprov.html
3108 INFO: checking PYZ
3115 INFO: Building because toc changed
3115 INFO: Building PYZ (ZlibArchive) XXX/pybuild/build/autoprov/PYZ-00.pyz
3408 INFO: Building PYZ (ZlibArchive) XXX/pybuild/build/autoprov/PYZ-00.pyz completed successfully.
3410 INFO: checking PKG
3415 INFO: Building because toc changed
3415 INFO: Building PKG (CArchive) PKG-00.pkg
5589 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
5592 INFO: Bootloader /usr/local/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit/run
5592 INFO: checking EXE
5598 INFO: Building because toc changed
5598 INFO: Building EXE from EXE-00.toc
5600 INFO: Appending archive to ELF section in EXE XXX/pybuild/dist/autoprov
5633 INFO: Building EXE from EXE-00.toc completed successfully.

On runnng the exe

[temp@localhost rpmfiles]$ sudo XXX/pybuild/dist/autoprov
Traceback (most recent call last):
  File "autoprov.py", line 1, in <module>
ModuleNotFoundError: No module named 'nginx'
[15311] Failed to execute script autoprov
[virsec@localhost rpmfiles]$

uname -a
Linux localhost.localdomain 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by peakwinter** [comment]
Hi!

I'm inclined to believe that this has something to do with how you're bundling your dependencies with pyinstaller. On a normal install of Python3 this library is fully supported. Can you run the script in question outside of pyinstaller (on your local system)?

**Comment by arymangupta** [comment]
yes it's working with without pyinstaller.
issue was with the verions of the pyinstaller.
